// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using customer_microservice.Datamodels;

namespace customer_microservice.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20210727004334_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("customer_microservice.Datamodels.AddressDataModel", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Address3")
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreateTimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("customer_microservice.Datamodels.CustomerDataModel", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BINARY(16)");

                    b.Property<byte[]>("AddressId")
                        .HasColumnType("BINARY(16)");

                    b.Property<DateTime>("CreateTimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CurrentAccountValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("CurrentCreditValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<decimal?>("TotalBuyValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id")
                        .HasName("pk_Customers");

                    b.HasIndex("AddressId");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("idx_FirstName");

                    b.HasIndex("LastName")
                        .HasDatabaseName("idx_LastName");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("customer_microservice.Datamodels.CustomerDataModel", b =>
                {
                    b.HasOne("customer_microservice.Datamodels.AddressDataModel", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
