apiVersion: v1
kind: Service
metadata:
  name: customerservice-lb
  labels:
    run: customerservice-svc
spec:
  selector:
    app: customerservice-svc
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerservice-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerservice-svc
  template:
    metadata:
      labels:
        app: customerservice-svc
    spec:
      serviceAccountName: default
      containers:
        - name: customermicroservice
          image: silmaril212/customermicroservice:v1.4
          imagePullPolicy: Always
          env:
            - name: MYSQL_SERVER
              value: "192.168.0.248"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "customer_microservice"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "VMware1!"
            - name: REDIS_CACHE_HOST
              value: "192.168.0.10"
            - name: REDIS_CACHE_PORT
              value: "6379"
            - name: REDIS_CACHE_PASSWORD
              value: "VMware1!"
            - name: REDIS_CACHE_USE
              value: "true"
